# Generated by Django 3.2.13 on 2022-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Author', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
            ],
        ),
    ]
